config/routes.rb
Myrun::Application.routes.draw do
  resources :runs
  resources :users
  get "logon/login"
  get "logon/logout"
  
  post "logon/login"
  post "logon/logout"

   root :to =>"users#index"

end

app/models/run.rb
class Run < ActiveRecord::Base
  belongs_to :user
  before_save :calc_average, :calc_calories
  
   def calc_average
     self.average = self.alltime.to_f/(self.distance/100)
    end
   
   def calc_calories
     self.calories = self.distance
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :runs
  before_save :encrypt
  has_attached_file :photo, :styles => { :small => "100x100>", :medium => "150x150>"},
                    :url  => "/users/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/users/:id/:style/:basename.:extension"                  
                    
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
  def encrypt
    self.userpass = Digest::SHA256.hexdigest("#{self.userpass}")
  end
  
  def self.digest(val)
    Digest::SHA256.hexdigest("#{val}")
  end
  
  def self.login(login, password)
    self.find_by_username_and_userpass(login, User.digest(password))
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  before_filter :authenticate
  helper_method :session_user
  protected 
  
  #Pegando os dados do usuario e alocando na sessão corrente
    def session_user
      @session_user ||= User.find(:first, :conditions => ['id = ?', session[:user]])
    end
  
  
  #Autenticação do Usuário
  def authenticate
    unless session[:user]
      session[:return_to] = request.request_uri
      render :controller => "logon", :action => "login"
      return false
    end
    return true
  end
end

app/controllers/logon_controller.rb
class LogonController < ApplicationController
  skip_before_filter :authenticate , :only => [:login]
  
  def login
    @user = User.login(params[:username], params[:userpass])
    if @user
      session[:user] = @user.id
      redirect_to(@user)
    else
     flash[:notice] = "Login ou Senha incorretos."
    end
  end

  def logout
    session[:user] = nil
  end

end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  skip_before_filter :authenticate
  def index
    @runs = Run.all
  end

  def show
    @run = Run.find(params[:id])
  end

  def new
    @run = Run.new(:user => User.find(params[:user_id]))
  end

  def edit
    @run = Run.find(params[:id])
  end

  def create
    @run = Run.new(params[:run])
      if @run.save
        redirect_to(@run, :notice => 'Run was successfully created.')
      else
        render :action => "new"
      end
  end

  def update
    @run = Run.find(params[:id])
      if @run.update_attributes(params[:run])
        redirect_to(@run, :notice => 'Run was successfully updated.')
      else
        render :action => "edit"
      end
  end

  def destroy
    @run = Run.find(params[:id])
    @run.destroy
    redirect_to(runs_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :authenticate
  
  def index
    @users = User.all
  end
  
  def personal_index
    @user = User.find_by_username_and_userpass(params[:username],params[:userpass])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @runs = Run.find(params[@run.id])
    @user.destroy
    @runs.destroy    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logon_helper.rb
module LogonHelper
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def calc_total
    Run.sum(:distance, :conditions => ['user_id =?', params[:id]])
  end
  
  def calc_week
    Run.sum(:distance, :conditions =>'DAY(day)>=DAY(curdate())-7 and MONTH(day)=MONTH(curdate())')
  end
  
  def calc_month
    Run.sum(:distance, :conditions => 'MONTH(day)=MONTH(curdate())')    
  end
  
  def calc_year
    Run.sum(:distance, :conditions => 'YEAR(day)=YEAR(curdate())')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrun</title>
	<script src='javascripts/application.js'></script>
	<script src='javascripts/jquery.js'></script>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body background="#C8D2D9">
<div id="menu">
	<ul>
		<% if session[:user] %>
			<li><%= link_to 'Home' %><li>
				<li><%= link_to 'MyRuns'  %><li>
		<% end %>	
		<li><%= link_to 'Login',  :controller => 'logon', :action => "login" %></li>
		<li><%= link_to 'Logout', :controller => 'logon', :action => "logout"  %></li>
	</ul>
</div>
<%= yield %>

</body>
</html>

app/views/logon/login.html.erb
<div id="login">
<h1>Login</h1>
<%= form_tag :action => "login" %> 
	<div class="field">
		Username:<br />
		<%= text_field_tag :username, params[:username] %> 
	</div>
	<div class="field"> 
		Password:<br />
		<%= password_field_tag :userpass, params[:userpass] %>
	</div> 
	<div class="actions">
		<%= submit_tag "Sign in" %> | <%= link_to 'SignUp', new_user_path %>
	</div>
</div>

app/views/logon/logout.html.erb
<div id="logout">
	<h1>Logout</h1>
	<p>Sessão Finalizada!</p>
</div>

app/views/runs/_form.html.erb
<%= form_for(@run) do |f| %>
  <%= f.hidden_field :user_id %>
  <% if @run.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@run.errors.count, "error") %> prohibited this run from being saved:</h2>

      <ul>
      <% @run.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    Distância (metros)<br />
    <%= f.text_field :distance %>
  </div><br />
  <div class="field">
    Data<br />
    <%= f.date_select :day, :order => [:day, :month, :year] %>
  </div><br />
  <div class="field">
    Tempo Gasto (minutos)<br />
    <%= f.text_field :alltime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/runs/edit.html.erb
<h1>Editando Treino</h1>

<%= render 'form' %>

<%= link_to 'Show', @run %> |
<%= link_to 'Back', user_path(@run.user_id) %>

app/views/runs/index.html.erb
<div id="contents">
<h1>Listando Treinos</h1>

<table border=1>
  <tr>
    <th>User</th>
    <th>Distance</th>
    <th>Day</th>
    <th>Tempo Gasto (minutos)</th>
    <th>Actions</th>
  </tr>

<% @runs.each do |run| %>
  <tr align="center">
    <td><%= run.user.name %></td>
    <td><%= run.distance %></td>
    <td><%= run.day.strftime("%d/%m/%Y") %></td>
    <td><%= run.alltime %></td>
    <td><%= link_to 'Show', run %>
    <%= link_to 'Edit', edit_run_path(run) %>
    <%= link_to 'Destroy', run, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Run', new_run_path %>
</div>

app/views/runs/new.html.erb
<h1>Cadastrando Novo Treino</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@run.user_id) %>

app/views/runs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @run.user.name %>
</p>

<p>
  <b>Distance:</b>
  <%= @run.distance %>
</p>

<p>
  <b>Day:</b>
  <%= @run.day %>
</p>

<p>
  <b>Alltime:</b>
  <%= @run.alltime %>
</p>


<%= link_to 'Edit', edit_run_path(@run) %> |
<%= link_to 'Back', user_path(@run.user_id) %>

app/views/users/_form.html.erb
<% form_for @user, :html => { :multipart => true } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 99 %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :size => 100 %>
  </div>
  <div class="field">
    <%= f.label :sexo %>
    <%= f.select :sexo, [["masculino","masculino"],["feminino","feminino"]] %>
  </div>
  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age, :size => 3 %>
    <%= f.label :peso %>
    <%= f.text_field :peso, :size => 3 %>
    <%= f.label :altura %>
    <%= f.text_field :altura, :size => 5 %>
  </div>
  <div class="field">
    Login
    <%= f.text_field :username %>
  </div>
  <div class="field">
	Password
    <%= f.password_field :userpass %>
  </div>
  <div>
  	<%= f.label :photo %>
  	<%= f.file_field :photo %> 
  </div><br /><br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="contents">
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', @user %>
</div>

app/views/users/index.html.erb
<div id="contents">
<h1>Listing users</h1>

<table border=1>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Username</th>
	<th>Picture</th>
    <th>Actions</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.username %></td>
	<td><%= link_to image_tag user.photo.url(:small) %></td>
    <td><%= link_to 'Show', user %>
    	<%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div id="contents">
	<h1>New user</h1>

	<%= render 'form' %>

	<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div id="contents">
<h1>Meus Treinos</h1><br />

<p id="notice"><%= notice %></p>
<%= link_to image_tag @user.photo.url(:small) %>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<div id="table">
	<table border=1>
		<tr>
			<th>Data da Corrida</th>
			<th>Distância Km</th>
			<th>Tempo Min</th>
			<th>Média Km/Min</th>
			<th>Calorias</th>
		</tr>
		<% @runs = Run.find_all_by_user_id(@user.id) %>
			<% @runs.each do |runs| %>
				<tr align="center">
					<td><%= runs.created_at.strftime("%d/%m/%Y") %></td>
					<td><%= runs.distance/1000%></td>
					<td><%= runs.alltime %></td>
					<td><%= runs.average %></td>
					<td><%= runs.calories %></td>
				</tr>	
			<% end %>	
	</table>
	<div id="total">
		<p>
			<b>Total Semana: <%= calc_week %> metros</b><br />
			<b>Total Mês: <%= calc_month %> metros</b><br />
			<b>Total Ano: <%= calc_year %> metros</b><br />
			<b>Total: <%= calc_total %> metros</b><br />
		</p>
	</div>
</div><br />
<%= link_to 'New Runs', new_run_path(@run, :user_id => @user.id) %> |
<%= link_to 'Edit User', edit_user_path(@user) %>
</div>